#!/usr/bin/env bash
# =============================================================================
# WHALE - Install Bacula Community: Director, Storage Daemon, File Daemon, Console
# Configures job "WhaleBackup" to back up WHALE_BACKUPS (default /var/backups/whale).
# Usage: sudo ./setup_bacula.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WHALE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "${WHALE_ROOT}/lib/common.sh" 2>/dev/null || true

WHALE_BACKUPS="${WHALE_BACKUPS:-/var/backups/whale}"
BACULA_CONF_D="${BACULA_CONF_D:-/etc/bacula/bacula-dir.d}"
BACULA_MAIN_CONF="${BACULA_MAIN_CONF:-/etc/bacula/bacula-dir.conf}"

log() { echo "[$(date +%Y-%m-%dT%H:%M:%S)] $*"; }
die() { log "ERROR: $*"; exit 1; }

require_root

# -----------------------------------------------------------------------------
# Install Bacula packages (Director, Storage Daemon, File Daemon, Console)
# -----------------------------------------------------------------------------
install_bacula_packages() {
  log "Installing Bacula Community (Director, Storage Daemon, File Daemon, Console)..."
  apt-get update -qq
  # Try meta-package first; fallback to individual components
  if apt-cache show bacula &>/dev/null; then
    apt-get install -y bacula
  else
    apt-get install -y bacula-director bacula-sd bacula-fd bacula-console || \
    apt-get install -y bacula-server bacula-client bacula-console || \
    die "Could not install Bacula packages. Install manually: bacula-director, bacula-sd, bacula-fd, bacula-console"
  fi
  log "Bacula packages installed."
}

# -----------------------------------------------------------------------------
# Deploy WhaleBackup job config (FileSet, Schedule, Job)
# -----------------------------------------------------------------------------
deploy_whale_job_config() {
  mkdir -p "$BACULA_CONF_D"
  mkdir -p "$WHALE_BACKUPS"

  # Use existing Client from default Director config (bacula-fd, server-fd, or hostname-fd)
  local existing_client="bacula-fd"
  if [[ -f "$BACULA_MAIN_CONF" ]]; then
    local detected
    detected=$(awk '/Client\s*\{/{p=1} p && /Name\s*=/{gsub(/.*Name\s*=\s*"|".*/,""); print; exit}' "$BACULA_MAIN_CONF" 2>/dev/null)
    [[ -n "$detected" ]] && existing_client="$detected"
  fi

  cat > "${BACULA_CONF_D}/whale-job.conf" << EOF
# WHALE - Bacula job to back up local WHALE backups (MySQL dumps, uploads, configs)
# Generated by setup_bacula.sh. Client = $existing_client (local File Daemon).

FileSet {
  Name = "WhaleBackupSet"
  Include {
    Options {
      signature = SHA1
      compression = GZIP
    }
    File = ${WHALE_BACKUPS}
  }
}

Schedule {
  Name = "WhaleDaily"
  Run = Full daily at 03:15
}

Job {
  Name = "WhaleBackup"
  JobDefs = "DefaultJob"
  Client = ${existing_client}
  FileSet = "WhaleBackupSet"
  Schedule = "WhaleDaily"
  Storage = File
  Pool = Default
  Messages = Standard
  Priority = 10
}
EOF
  log "Created ${BACULA_CONF_D}/whale-job.conf (Client=$existing_client)"

  # Append @include so Director loads our job (Bacula supports @path include)
  if [[ -f "$BACULA_MAIN_CONF" ]] && ! grep -q "whale-job.conf" "$BACULA_MAIN_CONF" 2>/dev/null; then
    echo "" >> "$BACULA_MAIN_CONF"
    echo "# WHALE WhaleBackup job" >> "$BACULA_MAIN_CONF"
    echo "@${BACULA_CONF_D}/whale-job.conf" >> "$BACULA_MAIN_CONF"
    log "Appended include for whale-job.conf to $BACULA_MAIN_CONF"
  else
    log "WhaleBackup config already included in Director."
  fi
}

# -----------------------------------------------------------------------------
# Ensure File Daemon (FD) allows Director - same host
# -----------------------------------------------------------------------------
ensure_fd_config() {
  local fd_conf="/etc/bacula/bacula-fd.conf"
  if [[ -f "$fd_conf" ]]; then
    if ! grep -q "Director.*whale" "$fd_conf" 2>/dev/null; then
      # Default Director in bacula-fd.conf is usually "bacula-dir"; no change needed for local backup
      log "File Daemon config present at $fd_conf"
    fi
  fi
}

# -----------------------------------------------------------------------------
# Enable and start Bacula services
# -----------------------------------------------------------------------------
enable_bacula_services() {
  for svc in bacula-director bacula-sd bacula-fd; do
    if systemctl list-unit-files --type=service 2>/dev/null | grep -q "^${svc}.service"; then
      systemctl enable "$svc" 2>/dev/null || true
      systemctl start "$svc" 2>/dev/null || true
      log "Started $svc"
    fi
  done
  log "Bacula services enabled and started."
}

# -----------------------------------------------------------------------------
# Verify bconsole and job list
# -----------------------------------------------------------------------------
verify_bconsole() {
  if command -v bconsole &>/dev/null; then
    log "bconsole is available. Test with: echo 'status director' | bconsole"
    if echo "list jobs" | bconsole &>/dev/null; then
      log "bconsole connection OK."
    else
      log "Warning: bconsole could not list jobs (check Director password in /etc/bacula/bconsole.conf)"
    fi
  else
    log "Warning: bconsole not in PATH (install bacula-console if needed)"
  fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
  log "=== Bacula setup for WHALE started ==="
  install_bacula_packages
  deploy_whale_job_config
  ensure_fd_config
  enable_bacula_services
  verify_bconsole
  log "=== Bacula setup finished ==="
  log "WhaleBackup job backs up: $WHALE_BACKUPS"
  log "Trigger from backup.sh with: echo 'run job=WhaleBackup yes' | bconsole"
}

main "$@"
